//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Levels/world.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Levels
{
    /// <summary>
    /// LDtk Enum for WorldEnums
    /// </summary>
    public enum DoorDestination
    {
        The_Hand,
        Joker
    }
}